-- CareerPilot AI — Phase 2 Increment A: embeddings + pgvector semantic search.
-- Additive only: no table/column changes (the vector(768) columns on jobs.embedding and
-- resumes.embedding already exist from V1), just the ANN indexes needed to make nearest-neighbor
-- search fast. Idempotent — hand-applied against the managed Neon instance, same convention as
-- V4–V10. Dropping these indexes has zero functional impact (search just falls back to a slower
-- sequential scan), and the whole feature is gated by EMBEDDINGS_ENABLED (default false).
--
-- HNSW + cosine ops: embeddings are generated by Gemini text-embedding-004 (768-d), and the
-- semantic-search query orders by the cosine distance operator (<=>), so the index opclass must be
-- vector_cosine_ops to be used. HNSW (vs IVFFlat) needs no training/list tuning and stays correct
-- as rows are inserted incrementally by the daily discovery run. Requires pgvector >= 0.5.0 (Neon).

CREATE INDEX IF NOT EXISTS idx_jobs_embedding_hnsw
    ON jobs USING hnsw (embedding vector_cosine_ops);

CREATE INDEX IF NOT EXISTS idx_resumes_embedding_hnsw
    ON resumes USING hnsw (embedding vector_cosine_ops);
