import { useQuery } from '@tanstack/react-query';
import { CheckCircle2, FileText, ScanLine, Sparkles, XCircle } from 'lucide-react';
import { api } from '@/lib/api';
import { Skeleton } from '@/components/ui/skeleton';
import { Dialog, DialogBody, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import type { JobMatchExplanation } from '@/types/workflow';

interface ExplainDialogProps {
  jobId: string | null;
  jobTitle?: string;
  onClose: () => void;
}

function Section({
  icon: Icon,
  title,
  items,
  tone,
}: {
  icon: typeof CheckCircle2;
  title: string;
  items: string[];
  tone: string;
}) {
  if (!items.length) return null;
  return (
    <div>
      <h4 className="mb-1.5 flex items-center gap-1.5 text-sm font-semibold text-foreground">
        <Icon className={`h-4 w-4 ${tone}`} /> {title}
      </h4>
      <ul className="space-y-1 pl-1">
        {items.map((it, i) => (
          <li key={i} className="flex gap-2 text-sm text-muted-foreground">
            <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-muted-foreground" />
            {it}
          </li>
        ))}
      </ul>
    </div>
  );
}

export function ExplainDialog({ jobId, jobTitle, onClose }: ExplainDialogProps) {
  const { data, isLoading, isError } = useQuery<JobMatchExplanation>({
    queryKey: ['jobs', 'explain', jobId],
    queryFn: async () => (await api.post(`/api/jobs/${jobId}/explain`)).data,
    enabled: !!jobId,
    staleTime: Infinity, // result is cached server-side; no need to refetch
  });

  return (
    <Dialog open={!!jobId} onOpenChange={(o) => !o && onClose()} size="lg">
      <DialogHeader onClose={onClose}>
        <DialogTitle>
          <span className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-primary" /> Why am I a match?
          </span>
        </DialogTitle>
        <DialogDescription>{jobTitle ?? 'AI-generated fit analysis for this role.'}</DialogDescription>
      </DialogHeader>
      <DialogBody className="space-y-5">
        {isLoading ? (
          <div className="space-y-3">
            {Array.from({ length: 4 }).map((_, i) => (
              <Skeleton key={i} className="h-16 rounded-lg" />
            ))}
            <p className="text-center text-xs text-muted-foreground">Analyzing your fit…</p>
          </div>
        ) : isError || !data ? (
          <p className="text-sm text-muted-foreground">
            Could not generate an explanation right now. Please try again shortly.
          </p>
        ) : (
          <>
            <Section icon={CheckCircle2} title="Matching skills" items={data.matchingSkills} tone="text-success" />
            <Section icon={XCircle} title="Skills to build" items={data.missingSkills} tone="text-warning" />
            <Section icon={FileText} title="Resume improvements" items={data.resumeImprovements} tone="text-primary" />
            <Section icon={ScanLine} title="ATS improvements" items={data.atsImprovements} tone="text-secondary" />
            {data.modelUsed && (
              <p className="pt-1 text-right text-[11px] text-muted-foreground">Generated by {data.modelUsed}</p>
            )}
          </>
        )}
      </DialogBody>
    </Dialog>
  );
}
